services:
    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: Europe/Warsaw
        container_name: mailpit-php
        volumes:
            - ./:/app
            - './docker/php/conf.d:/usr/local/etc/php/conf.d'
            - 'php_composer_data:/root/.composer'
        networks:
            - network_mailer
            - network_rabbit

    mailer-www:
        build: ./docker/www
        container_name: mailpit-www
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
            - ./docker/www/conf.d:/etc/nginx/conf.d
        networks:
            - network_mailer

    db:
        image: "mariadb:11"
        container_name: mailpit-db
        volumes:
            - mailer_db_data:/var/lib/mysql
        networks:
            - network_mailer
        ports:
            - "3307:3306"
        environment:
            - TZ=UTC
            - MYSQL_ROOT_PASSWORD=root
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        ports:
            - "8025:8025"
        networks:
            - network_mailer

    mailer-worker:
        build:
            context: ./docker/php
        command: php bin/console messenger:consume rabbitmq --time-limit=3600 --memory-limit=128M
        restart: always
        networks:
            - network_mailer
            - network_rabbit
        volumes:
            - ./:/app

volumes:
    mailer_db_data:
    php_composer_data:

networks:
  network_mailer:
    name: network_mailer
    driver: bridge
  network_rabbit:
    external: true
    name: network_rabbit
